name: CI-CD

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t teentalktalk .
        
    - name: 설정 파일 생성
      run: |
        echo "서버 설정 파일을 생성합니다..."
        echo "export const serverConfig = {" >> serverConfig.js
        echo "  ipAddress: '${{ secrets.PUBLIC_IP }}'," >> serverConfig.js
        echo "  password: '${{ secrets.SERVER_PASSWORD }}'" >> serverConfig.js
        echo "};" >> serverConfig.js

    - name: Node.js 애플리케이션 빌드
      run: |
        cd app
        npm install

    - name: 서버 배포
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 223.130.156.202 >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/id_rsa -p 22 root@223.130.156.202 '
          echo "Connected to NCP Server"
          docker pull teentalktalk/teentalktalk:latest
          docker compose up -d
        '
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
